### ISSUE TITLE
[java] Error while processing class when EnumMap is used in PMD 5.8.0

### ISSUE THREAD

**Issue by Macarse** [pmd/pmd#471]
**Rule Set:** N/A

**Description:** Error while processing class when EnumMap is used in 5.8.0

**Code Sample demonstrating the issue:**

```
// MyEnum.java
public enum MyEnum {
    ONE,
    TWO
}

// Some other java class
EnumMap enumMap = new EnumMap(MyEnum.class);
```

**Running PMD through:** *Gradle*

**Comment by Macarse** [comment]
There is also a similar issues with enums when using something like

`EnumSet<MyClass> x = EnumSet.noneOf(MyClass.class);`

**Comment by oowekyala** [comment]
Hi, can you provide a stack trace of the error, and the name of the rule which caused it?

**Comment by Macarse** [comment]
@oowekyala I run through gradle so I am not sure how to get that information for you.
When I run `./gradlew pmd --debug` I haven't found anything pmd related. Is there other way?

**Comment by jsotuyod** [comment]
@Macarse `./gradlew pmd --debug` should indeed output all debug info from PMD itself, and the root exception should be visible.

**Comment by jsotuyod** [comment]
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.getNextTypeDefinition(ClassTypeResolver.java:449)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.getNextTypeDefinition(ClassTypeResolver.java:442)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.getDefaultUpperBounds(ClassTypeResolver.java:524)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:262)
        at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceType.jjtAccept(ASTClassOrInterfaceType.java:23)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:58)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:612)
        at net.sourceforge.pmd.lang.java.ast.ASTReferenceType.jjtAccept(ASTReferenceType.java:25)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:210)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:605)
        at net.sourceforge.pmd.lang.java.ast.ASTType.jjtAccept(ASTType.java:22)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:162)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:579)
        at net.sourceforge.pmd.lang.java.ast.ASTFieldDeclaration.jjtAccept(ASTFieldDeclaration.java:23)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:46)
        at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBodyDeclaration.jjtAccept(ASTClassOrInterfaceBodyDeclaration.java:41)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:42)
        at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBody.jjtAccept(ASTClassOrInterfaceBody.java:21)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:18)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:271)
        at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceDeclaration.jjtAccept(ASTClassOrInterfaceDeclaration.java:31)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:158)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:229)
        at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept(ASTTypeDeclaration.java:35)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:56)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:10)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:138)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:200)
        at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:41)
        at net.sourceforge.pmd.lang.java.typeresolution.TypeResolutionFacade.initializeWith(TypeResolutionFacade.java:18)
        at net.sourceforge.pmd.lang.java.AbstractJavaHandler$5.start(AbstractJavaHandler.java:95)
        at net.sourceforge.pmd.SourceCodeProcessor.usesTypeResolution(SourceCodeProcessor.java:151)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:179)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:97)
````

@WinterGrascph I'll have a go at this, I'll let you know if we need anything.
@adangel we may need to do a 5.8.1 release for this. We should probably wait however a few days to make sure no other issues arise..

**Comment by jsotuyod** [comment]
@Macarse in the meantime, setting the generics for `EnumMap` or `EnumSet` will work. You probably should anyway...

**Comment by WinterGrascph** [comment]
I've submitted a PR with a fix. Thanks for reporting the issue.

**Comment by jsotuyod** [comment]
This was fixed in https://github.com/pmd/pmd/commit/3bd69b15f1942922991fe85cb6723ddf715b5e10 will be part of 5.8.1

**Comment by Reissner** [comment]
I use pmd 5.8.1 with maven 3.3.9

Still have an issue like this: 
 
[INFO] --- maven-pmd-plugin:3.8:pmd (default-cli) @ l2r ---
[WARNING] There are 4 PMD processing errors:
[WARNING] /home/ernst/Software/src/main/java/eu/simuline/arithmetics/AbstractRNNumber.java: Error while processing /home/ernst/Software/src/main/java/eu/simuline/arithmetics/AbstractRNNumber.java
/home/ernst/Software/src/main/java/eu/simuline/arithmetics/GArray.java: Error while processing /home/ernst/Software/src/main/java/eu/simuline/arithmetics/GArray.java
/home/ernst/Software/src/main/java/eu/simuline/arithmetics/left2right/WeakSlaveCollection.java: Error while processing /home/ernst/Software/src/main/java/eu/simuline/arithmetics/left2right/WeakSlaveCollection.java
/home/ernst/Software/src/main/java/eu/simuline/util/ListMap.java: Error while processing /home/ernst/Software/src/main/java/eu/simuline/util/ListMap.java

pom.xml: 
     
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-pmd-plugin</artifactId>
        <version>${versionPmdMvnPlugin}</version>
	
	
        <dependencies>
          <dependency>
            <groupId>net.sourceforge.pmd</groupId>
            <artifactId>pmd-core</artifactId>
            <version>${versionPmd}</version>
          </dependency>
          <dependency>
            <groupId>net.sourceforge.pmd</groupId>
            <artifactId>pmd-java</artifactId>
            <version>${versionPmd}</version>
          </dependency>
        </dependencies>

        <configuration>
	  <format>xml</format>
	  <skip>false</skip>
	  <skipEmptyReport>false</skipEmptyReport>
	  
	  <includeTests>false</includeTests>
          <rulesets>
	    <ruleset>${maven.pmd.rulesetfiles}</ruleset>
          </rulesets>
          <excludes>
	    <exclude>dk/ange/octave/**/*.java</exclude>
 	    <exclude>info/relm/**/*.java</exclude>

            <exclude>eu/simuline/calc/CalcLexer.java</exclude>
            <exclude>eu/simuline/calc/CalcParser.java</exclude>
	    <include>eu/simuline/calc/Calc*Listener.java</include>
	    <include>eu/simuline/calc/Calc*Visitor.java</include>

 
            <exclude>eu/simuline/fpga/SvfLexer.java</exclude>
            <exclude>eu/simuline/fpga/SvfParser.java</exclude>
	    <include>eu/simuline/fpga/Svf*Listener.java</include>
	    <include>eu/simuline/fpga/Svf*Visitor.java</include>

	    <exclude>eu/simuline/matlab/MatlabParser.java</exclude>
            <exclude>eu/simuline/matlab/MatlabLexer.java</exclude>
 	    <exclude>eu/simuline/matlab/Matlab*Listener.java</exclude>
	    <exclude>eu/simuline/matlab/Matlab*Visitor.java</exclude>

            <exclude>eu/simuline/names/RulesLexer.java</exclude>
            <exclude>eu/simuline/names/RulesParser.java</exclude>
	    <include>eu/simuline/names/Rules*Listener.java</include>
	    <include>eu/simuline/names/Rules*Visitor.java</include>

  
            <exclude>eu/simuline/relana/parser/*Lexer.java</exclude>
            <exclude>eu/simuline/relana/parser/*Parser.java</exclude>
            <exclude>eu/simuline/relana/parser/CClassLexer.java</exclude>
            <exclude>eu/simuline/relana/parser/CClassParser.java</exclude>
	    <include>eu/simuline/relana/parser/CClass*Listener.java</include>
	    <include>eu/simuline/relana/parser/CClass*Visitor.java</include>

            <exclude>eu/simuline/relana/parser/SClassLexer.java</exclude>
            <exclude>eu/simuline/relana/parser/SClassParser.java</exclude>
	    <include>eu/simuline/relana/parser/SClass*Listener.java</include>
	    <include>eu/simuline/relana/parser/SClass*Visitor.java</include>

            <exclude>eu/simuline/relana/parser/FormulaLexer.java</exclude>
            <exclude>eu/simuline/relana/parser/FormulaParser.java</exclude>
 	    <include>eu/simuline/relana/parser/Formula*Listener.java</include>
	    <include>eu/simuline/relana/parser/Formula*Visitor.java</include>

            <exclude>eu/simuline/tex/TexLexer.java</exclude>
	    <exclude>eu/simuline/tex/TexParser.java</exclude>
            <exclude>eu/simuline/tex/Tex*Listener.java</exclude>
	    <exclude>eu/simuline/tex/Tex*Visitor.java</exclude>

 	    <exclude>org/webmacro/parser/BackupCharStream.java</exclude>
	    <exclude>eu/simuline/util/UIManagerDefaults.java</exclude>
          </excludes>
	  <outputDirectory>${project.basedir}/target/site/</outputDirectory>
        </configuration>
      </plugin>
Is there a way to see where the errors occur in more detail?

**Comment by jsotuyod** [comment]
You can run Maven with `-X` flag and you should be able to get a full stacktrace.

Please, provide such stacktrace along with source from `eu/simuline/util/ListMap.java` so we can reproduce the issue.

**Comment by Reissner** [comment]
Sorry, no stacktrace came out. also tried with mvn -e -X nothing. 

I can give you the file ListMap.java
[ListMap.java.txt](https://github.com/pmd/pmd/files/1200943/ListMap.java.txt)
